# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the version of Node.js you need

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build # If you have a build step

    - name: Publish to npm
      if: github.ref == 'refs/heads/main' # Publish only on main branch
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use the npm token secret
      run: |
        npm version patch # or minor/major as needed
        npm publish
